name: cf_rna-1.0.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::r-base>=4.0
  - conda-forge::r-rcolorbrewer>=1
  - conda-forge::r-plyr=1.8.6
  - conda-forge::r-readr=1.4.0
  - conda-forge::r-nbclust>=3.0
  - conda-forge::r-stringr=1.4.0
  - conda-forge::r-ggplot2=3.3.3
  ## bioconda packages
  - bioconda::bioconductor-topgo=2.42.0
  - bioconda::bioconductor-complexheatmap=2.6.2
  - bioconda::bioconductor-deseq2=1.30.1
  - bioconda::bioconductor-org.hs.eg.db=3.12.0
